apiVersion: v1
kind: Secret
metadata:
  name: app-secret
type: Opaque
stringData:
  DB_URL: "${DB_URL}"
  DB_USER: "${DB_USER}"
  DB_PASS: "${DB_PASS}"
  ACCESS_TOKEN: QVBQX1VTUi01NzA4NjQwNTY0MDYzMzQyLTA3MTYxNS03YTY5NjY1NWVlNzI0ZmExNzNiMzFkMmEyOTU5ZjhiOS0yNDIyMTg4NTQ=
  CLIENT_ID: NTcwODY0MDU2NDA2MzM0Mg==
  CLIENT_SECRET: Q29pTE1CZXRadzNveHN5dGlEeEZDOElqWVEyMVRLZTE=
  NOTIFY_URL: aHR0cHM6Ly9icm9rZW4taG9yc2UtMTAud2ViaG9vay5jb29s
  PUBLIC_KEY: QVBQX1VTUi00OGJmMmRkZS00MmUyLTRmZWItYTkzZS0zMDYwOTgzMDE1NWM=
  USER_ID: MjQyMjE4ODU0
  WEBHOOK_SECRET: MGEyZDMxZDNiNzk5ODIwNDVlMjIyZmYyMDAxZDFlNDhjMTEzZGE2YzllYTYxNWVlNTE0YTZlYzUzMWRhZDlkZQ==
  JWT_SECRET: YXBwX3Vzci03OGQzMTFmYi0wMTA2LTRmODktODI3OC1iYjk2NzAwNjJkNTc=