apiVersion: v1
kind: Service
metadata:
  name: app-svc
  labels:
    app: fastfood
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8080"
spec:
  selector:
    app: fastfood
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30080
  type: NodePort