apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  labels:
    app: promtail
data:
  promtail-config.yml: |
    server:
      http_listen_port: 9080
      grpc_listen_port: 0

    positions:
      filename: /tmp/positions.yaml

    clients:
      - url: http://loki.default.svc.cluster.local:3100/loki/api/v1/push

    scrape_configs:
      - job_name: kubernetes-logs
        static_configs:
          - targets:
              - localhost
            labels:
              job: kubernetes-logs
              __path__: /var/log/containers/*.log
              __host__: ${HOSTNAME}
        pipeline_stages:
          - docker: {}